name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main  # Verifique se sua branch se chama main ou master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: meuprojetoiot-c9370
          channelId: live
